### ISSUE TITLE
MPC5.0 图标未正确显示

### ISSUE THREAD

**Issue by kkzhang3** [ymwang78/TaijiControl#10]
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/8de088d8-e8fb-4644-aecd-860f623a8b10)

1. 图标未正确显示
2. 移除打印符号

**Comment by ymwang78** [comment]
图标已经修复，打印应该是个功能，可以打印趋势图等，确定放弃后在做。

**Comment by kkzhang3** [comment]
MPC5.0.3.1确认已修复。
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/a829333d-9a49-4ef5-9baa-4c98d215d11c)
