### ISSUE TITLE
RealGOgui 界面与授权绑定

### ISSUE THREAD

**Issue by kkzhang3** [ymwang78/TaijiControl#11]
RealGOgui界面启动时需检查并显示授权，防止gui启动而RealGOShell服务未启动。

**Comment by ymwang78** [comment]
在TaijiMPC狗存在的情况下，读取狗的授权
![image](https://github.com/ymwang78/TaijiControl/assets/8255960/b100aa04-9905-42ad-a0fc-f25f76be0841)
![image](https://github.com/ymwang78/TaijiControl/assets/8255960/dd8cb2cd-c04d-40de-8440-4e756b44a378)

在狗不存在或者授权失效的情况下，读取软License：
![image](https://github.com/ymwang78/TaijiControl/assets/8255960/b59631b6-ae3b-4cf8-b8c3-b9f62436d00b)
试用版在下方显示获取授权请求码，发送给我们，我们生成授权码后发给对方，对方在输入授权码里输入。

![image](https://github.com/ymwang78/TaijiControl/assets/8255960/8b21a781-76a0-4c3d-bb2c-a7d7ded075c3)
![image](https://github.com/ymwang78/TaijiControl/assets/8255960/47f258d2-6fd6-4a30-a298-4d4b7c524437)
![image](https://github.com/ymwang78/TaijiControl/assets/8255960/85d21e18-d496-41b6-833d-cf17b3e71caa)
