### ISSUE TITLE
MPC的Controller-DV界面中未能正确显示ON OFF WARM

### ISSUE THREAD

**Issue by kkzhang3** [ymwang78/TaijiControl#2]
在安诺的现场发现，Controller DVs 的界面的右下角，未能正确显示ON OFF WARM。
此bug不影响现场试用。
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/d01d81a2-cb2b-4554-aa35-d7504fcc29ca)

**Comment by ymwang78** [comment]
5.0.2.3 开始解决了
