### ISSUE TITLE
MPC5.0 辨识一致性问题

### ISSUE THREAD

**Issue by kkzhang3** [ymwang78/TaijiControl#23]
_NEW4.ojp文件中，使用1/3的数据辨识得到B级模型，1/2的数据辨识得到B或C级模型，使用3/4的数据辨识得到B级模型，使用全部数据辨识得到B或C级模型。
为何不是使用的数据越多得到的模型越好？
（1）使用1/3数据辨识
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/47c27ead-7d89-4626-abd3-97dd2407b7d0)
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/d4dbfb1e-1441-4533-9b5e-7ae44cd7bc23)
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/62fe617d-9482-47a9-b625-900a2f2a2054)

（2）使用1/2数据辨识（数据上看差于1/3）
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/4f6aee81-9942-44ea-b9fc-4bec6123cd1c)
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/9affc1d6-b0c3-4484-9394-e89867506e45)
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/5eacb10d-5695-4f37-b236-a9ed42f28055)

（3）使用3/4数据辨识（好于1/2）
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/c4b4d823-456d-4fbf-9c60-2ba3f7dfb3d7)
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/edf4e6d0-ffcc-4b07-8549-474499f9f2f6)
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/5aba2a77-700d-4992-a15c-0a9aebe5c936)

（4）使用全部数据辨识 (差于1/3、1/2、3/4)
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/c779835e-f253-49cc-82a8-af395ddf9c9e)
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/7c30330e-271c-4dc0-b5b2-633c2af3741d)
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/6e644fea-bfb2-4537-beec-31d2c1a293a9)

工程文件可从此处下载：
[_NEW4.zip](https://github.com/ymwang78/TaijiControl/files/15046442/_NEW4.zip)

**Comment by ymwang78** [comment]
辨识库更新了，待确认解决

**Comment by kkzhang3** [comment]
经过测试MPC5.0.3.2已改进。
