### ISSUE TITLE
OPT 全重系数应该怎么调（optimizing time factor），另外这个factor本身比较难键入

### ISSUE THREAD

**Issue by FengMountain** [ymwang78/TaijiControl#25]
MPC目前版本为v5.0.3.1(tj010=0.37.3)

**Comment by kkzhang3** [comment]
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/a473d307-c6e9-4d64-b0d5-5525d6d34660)
在控制器启动后，由于按采样时间刷新，导致难以输入。预计下个版本修复。
Optimizing time factor初始默认值是6，数字越大优化速度越慢。请在下个版本(tj010>=0.37.4)中使用。

**Comment by ymwang78** [comment]
我看了下这里是定时从PROJECT刷出来的，不太清楚这里的逻辑，需要 讲解一下再修正

**Comment by kkzhang3** [comment]
v5.0.3.2
控制器启动后修改Optimizing Time Factor应该弹出二次确认对话框(Are you sure?)
目前不确定是否修改成功。

**Comment by ymwang78** [comment]
原来的代码是没有这个提示功能，我加了。
