### ISSUE TITLE
Tai-Ji MPC 5.0 测试界面绘图区域当前时间坐标快一拍

### ISSUE THREAD

**Issue by kkzhang3** [ymwang78/TaijiControl#33]
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/4e947b47-aadc-4a79-8fbc-74722f2163f9)

需要讨论确认后修改。

**Comment by ymwang78** [comment]
<img width="546" alt="1715997932728" src="https://github.com/ymwang78/TaijiControl/assets/8255960/6595214b-125d-4432-96f4-b09885e1be51">
黄线往前退了一格表示还未执行，分割线不动，表示新数据的时间点
