### ISSUE TITLE
MPC5.0.3.2 DV辨识精度问题

### ISSUE THREAD

**Issue by kkzhang3** [ymwang78/TaijiControl#36]
测试了一个2MVs, 1DV, 3CVs的系统。
系统说明见
https://github.com/kkzhang3/pySimulator/blob/main/modules/TrainingMIMO_2x3/doc/TestGuide.md

被控对象的响应时间约为150，进行了约2600的测试与采集，DV-CV2的模型仍不理想。
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/88c52532-aafa-46f4-ba1a-4d081f66357c)

![image](https://github.com/ymwang78/TaijiControl/assets/78284297/4c6c586a-6113-41a8-b846-206bc3f82885)

![image](https://github.com/ymwang78/TaijiControl/assets/78284297/3ce76405-9bed-455c-b747-89bdbf0fcc7c)

以下是工程文件：
[mimo2x3.zip](https://github.com/ymwang78/TaijiControl/files/15211578/mimo2x3.zip)

**Comment by YucaiZhu2** [comment]
Its normal

**Comment by kkzhang3** [comment]
Thanks.
