### ISSUE TITLE
TaiJi MPC 5.0.3文本翻译问题

### ISSUE THREAD

**Issue by Piggezy** [ymwang78/TaijiControl#37]
中文翻译，S矩阵系数的中文含义为“输出增量权重”、R矩阵系数的中文含义为“输入增量权重”，参数整定助手里和在线控制器里的名字应当一样；仿真控制器里也有同样的问题。
![image](https://github.com/ymwang78/TaijiControl/assets/133301797/d290235f-b494-4769-b29c-56f6bec36f84)
英文版同理，可以改得更严谨一些。
![image](https://github.com/ymwang78/TaijiControl/assets/133301797/86b6899a-fc49-46d9-8f26-08bb93cbd7e3)

其他：可以统一一下英文大小写。例如：Variant Range， V和R都大写；但Increment weight，I大写，w小写。
<img width="281" alt="image" src="https://github.com/ymwang78/TaijiControl/assets/133301797/5251984a-f97e-4db9-b9c6-0fd8d1befc91">

**Comment by ymwang78** [comment]
![image](https://github.com/ymwang78/TaijiControl/assets/8255960/eef19fcd-c9d1-4368-8c78-6570bbc0a2ac)
![image](https://github.com/ymwang78/TaijiControl/assets/8255960/05dff08f-0ae4-4c85-8670-40ef48f9a7c0)
