### ISSUE TITLE
TaiJi MPC 5.0.x 覆盖安装时start.py被覆盖

### ISSUE THREAD

**Issue by Piggezy** [ymwang78/TaijiControl#38]
如题, HostVM文件夹里的start.py被覆盖掉了，PyTaiji/softesensing里的start.py没有被覆盖掉。建议：两处的start.py都不应该被覆盖掉。

**Comment by Piggezy** [comment]
若被覆盖且没有备份，软测量老脚本start.py可在PyTaiji/softesensing文件夹里找到

**Comment by ymwang78** [comment]
这地方有个矛盾，对于普通用户来说是不会修改这个PY的，如果我们有升级，不覆盖会导致错误。
对于我们自己有修改的，我们应该另存文件名，可以通过hostvm.xml里修改入口。
暂时没有想到两全的办法。
