### ISSUE TITLE
自动打包的python环境下载到本地后无法使用pip或jupyter

### ISSUE THREAD

**Issue by kkzhang3** [ymwang78/TaijiControl#4]
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/ff824c9c-e788-4f8f-8905-921c4b2a37e4)

**Comment by kkzhang3** [comment]
pip的使用可以使用
python -m pip list
替代

**Comment by kkzhang3** [comment]
jupyter notebook的使用可以用
python -m notebook
代替

**Comment by ymwang78** [comment]
确认pip.exe或者jupyter.exe是安装时候由distlib做的对python代码的一个包装，里面包含了python.exe的绝对路径，所以只能采取上述办法，或者加一个bat来解决。
