### ISSUE TITLE
MPC中键入OPC Server Name不生效 

### ISSUE THREAD

**Issue by kkzhang3** [ymwang78/TaijiControl#5]
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/20765d16-2c6e-43e8-a095-f1d78707ec69)

**Comment by ymwang78** [comment]
这是由于RecentFile列表里的文件不存在还去读取，导致所有数据被清空，加了文件存在判断后解决。

**Comment by kkzhang3** [comment]
确认MPC5.0.3.1已修复。
