### ISSUE TITLE
HostVM的启动问题

### ISSUE THREAD

**Issue by kkzhang3** [ymwang78/TaijiControl#50]
双击hostvm.exe控制台闪退。
能否修改为双击hostvm.exe执行控制台hostvm.exe --console的效果？
如果重复启动hostvm，是否应增加端口检测？

**Comment by ymwang78** [comment]
同目录下增加了console.bat，双击运行控制台模式
端口重复会提示：
[16:27:48.769][E][60276]{zce_acceptor::do_listen}       listen|127.0.0.1|36001|-4091|
