### ISSUE TITLE
HostVM卸载

### ISSUE THREAD

**Issue by kkzhang3** [ymwang78/TaijiControl#51]
可否在hostvm目录下增加一个uninstall.exe，双击就停止并卸载hostvm服务。

**Comment by ymwang78** [comment]
下一版本会带一个uninsta.bat 和 install.bat
uninsta.bat实现卸载，需要以管理员权限运行，代码如下：
@echo off
cd /d %~dp0
HostVM.EXE --stop HostVM
HostVM.EXE --uninstall HostVM
pause
