### ISSUE TITLE
MPC5.0 自动创建工程失败

### ISSUE THREAD

**Issue by kkzhang3** [ymwang78/TaijiControl#6]
MPC5.0自动创建的工程无法保存。
重写方法：
1. 清空ini文件中的RecentFile
2.  打开MPC，MPC会自己新建一个工程
3. 这个工程无法保存

![image](https://github.com/ymwang78/TaijiControl/assets/78284297/34ac1e00-3cbb-48e1-8dc0-47efa48b7a83)

**Comment by ymwang78** [comment]
这应该和上一问题原因相同，由于RecentFile列表里的文件不存在还去读取，导致所有数据被清空，加了文件存在判断后解决。

**Comment by kkzhang3** [comment]
确认MPC5.0.3.1已修复。
