### ISSUE TITLE
MPC5.0 辨识界面期望矩阵与变量选择有冲突

### ISSUE THREAD

**Issue by kkzhang3** [ymwang78/TaijiControl#8]

**Comment by ymwang78** [comment]
改成有错误仍然提示，但还是允许修改。在辨识前再一次检查，如果发现有错，就不允许辨识。

**Comment by kkzhang3** [comment]
5.0.3.1版本做了一些改进，但仍然存在一些问题。
比如AGMill4.ojp文件中，unselect CV4 与 DV4仍然报告DV4有问题。不符合逻辑。
希望修改为未勾选变量无视期望矩阵。
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/c56190e3-5a15-4037-a22d-1be03f807b7a)
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/08273509-c624-4099-81ed-78a3e4475906)
![image](https://github.com/ymwang78/TaijiControl/assets/78284297/ba8089ab-bffd-40a0-9614-6bbf43307506)

[AGMill4.zip](https://github.com/ymwang78/TaijiControl/files/15038023/AGMill4.zip)

**Comment by ymwang78** [comment]
这个测试是不是还需要一个位号创建脚本？

**Comment by kkzhang3** [comment]
5.0.3.2 已改进。
